### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by spaenleh** [graasp/client#636]
Changes planned for the next iteration:
- [x] graasp/graasp-builder#1431

UI Bugs:
- [ ]  Flicker when selecting "created by me"
- [x] graasp/graasp-builder#1433

Standing bugs:
- [ ] When home is empty, copy modal crashes
- [ ]
